version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Setup tools
          command: apk update && apk add --no-progress gcc make cppcheck libc-dev ca-certificates
      - run:
          name: Build
          command: make streams_test
      - run:
          name: Test
          command: mkdir -p test-results/streams && ./streams_test -t --xml-output=test-results/streams/test.xml
      - store_test_results:
          path: test-results
