version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Setup tools
          command: apk update && apk add gcc make cppcheck libc-dev
      - run:
          name: Build
          command: make streams_test
      - run:
          name: Test
          command: mkdir test-output && ./streams_test --xml-output=test-results/test.xml
      - store_test_results:
          path: test-results
